### PR TITLE
[#5] Create first draft of Tui with sample process

### LINKED ISSUE #5: Think of convenient interface for inputting arguments
We're are going to use Haskell library `brick` for TUI implementation.

See some examples here:

* https://github.com/JackKiefer/herms
* https://github.com/8Gitbrix/2048Haskell

But before implementing TUI, we need to invent interface first. This issue is only about thinking on convenient interface.

Let's consider for example that you're going to work with messages like these ones:

```proto
message Position {
  required double lat = 1;
  required double lon = 2;

  optional string geocode = 10;
  optional double accuracy = 11;
  optional string description = 12;
}

message Image {
  required string canonicalName = 1;
  required string url = 2;

  optional Position position = 10;
  optional Image high_res = 11;
}

enum Mood {
  Excited = 0;
  Relaxed = 1;
  Tired = 2;
  Stressed = 3;
  Sick = 4;
}
```

It should be possible via implemented interface to choose message type and specify its fields.

Take into consideration the following:

1. `required` and `optional` fields.
2. enums
3. `repeated` fields
4. Default values.
5. `oneof`
6. Nested messages.

### PR DESCRIPTION
**Pull request by TejasSC**
Resolves #5

### CODE REVIEW

**Comment by ChShersh** [comment]
@TejasSC Could you attach some screenshots in the comments to this PR?

**Comment by TejasSC** [comment]
screen shot 2018-08-23 at 2 26 07 pm
screen shot 2018-08-23 at 2 26 26 pm
screen shot 2018-08-23 at 2 26 43 pm
screen shot 2018-08-23 at 2 29 33 pm

**Comment by ChShersh** [comment]
Looks great! For now the goal is to have some edit boxes inside terminal so we can construct message (even if it's just our hardcoded `SearchRequest` message). Basically, hardcode graphical view for `SearchRequest` and give ability to change values of the fields and show serialized message.

**Comment by TejasSC** [comment]
screen shot 2018-08-24 at 5 37 47 pm
screen shot 2018-08-24 at 5 37 04 pm
screen shot 2018-08-24 at 5 36 21 pm
screen shot 2018-08-24 at 5 36 01 pm

**Comment by TejasSC** [comment]
screen shot 2018-08-24 at 5 54 37 pm

So now it only works if I type in "SearchRequest" and "query" explicitly as Message name and Field name. 

How can I make the serialised representation work so that it doesn't fail on different inputs?

**Comment by TejasSC** [comment]
So now whenever I try to edit protobuf2.proto in the Tui.hs file, it never really works due to the following error. 
Hence, I still can't generate custom messages now. 

screen shot 2018-08-27 at 6 00 58 pm
screen shot 2018-08-27 at 6 00 35 pm

**Pull request merged**
